#pragma once
#include <Arduino.h>
const char kWebUi[] PROGMEM = R"HTML(<!doctype html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Robot AI · Kontrol</title><style>
:root{color-scheme:dark;--bg:#0c1423;--card:#172237;--line:#2b3d58;--accent:#5ee5c2;--text:#e9f1fb}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:16px system-ui,sans-serif}main{max-width:1050px;margin:auto;padding:28px 20px}header{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}h1{margin:4px 0;font-size:30px}.eyebrow{color:var(--accent);font-size:12px;letter-spacing:2px}.badge{background:#24413e;color:var(--accent);padding:8px 12px;border-radius:20px}.grid{display:grid;grid-template-columns:1.1fr 1fr;gap:18px}.card{background:var(--card);border:1px solid var(--line);border-radius:18px;padding:22px}h2{font-size:19px;margin:0 0 18px}label{display:block;margin:16px 0 7px;color:#bccce0}input,button{font:inherit;border-radius:10px;border:1px solid var(--line);padding:12px;background:#0d192b;color:var(--text)}input:not([type=checkbox]):not([type=range]){width:100%}button{cursor:pointer;touch-action:none}button:hover{border-color:var(--accent)}button:disabled{opacity:.5;cursor:default}.primary{background:var(--accent);color:#102a29;font-weight:700}.stop{background:#b33550;color:white;font-weight:800;width:100%;margin-top:18px;padding:18px}.directions{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;max-width:300px;margin:20px auto}.directions button{min-height:64px;font-size:24px}.wide{grid-column:1/-1}.row{display:flex;gap:10px;align-items:center}.row button{flex:1}input[type=range]{width:100%;accent-color:var(--accent);padding:0}pre{white-space:pre-wrap;overflow-wrap:anywhere;color:#adbed3;font-size:13px}.muted{color:#9eafc6;font-size:13px;line-height:1.6}#message{min-height:24px;color:var(--accent);overflow-wrap:anywhere}.warning{color:#ffd28a}details{margin-top:20px}summary{cursor:pointer}output{float:right;color:var(--accent)}@media(max-width:720px){.grid{grid-template-columns:1fr}header{align-items:flex-start;gap:12px}h1{font-size:25px}.card{padding:18px}}
</style></head><body><main><header><div><div class="eyebrow">ROBOT AI / LOCAL CONTROL</div><h1>Pusat kendali robot</h1><div class="muted">Dua roda · Dua tangan · Laser</div></div><div><span class="badge" id="version">Versi…</span><p class="muted" id="connection" role="status">Menghubungkan…</p></div></header>
<div class="grid"><section class="card"><h2>Koneksi & kendali</h2><p class="muted">Akses lokal tanpa token. Satu sesi kendali aktif pada satu waktu.</p><div class="row"><button id="modeManual" aria-pressed="true" class="primary">Manual</button><button id="modeAuto" aria-pressed="false">Auto</button></div><p class="muted" id="modeInfo">Manual: tombol dan slider. Auto: engine laptop melalui API.</p><div class="row"><button id="connect">Coba koneksi</button><button id="acquire">Aktifkan manual</button></div><p id="message" role="status">Membaca status robot…</p><p id="pwmInfo" class="muted">PWM roda: menunggu status.</p>
<label>Daya motor <output id="powerValue">30%</output></label><input id="power" type="range" min="0" max="100" value="30">
<div class="directions"><span></span><button data-drive="forward" aria-label="Maju">↑</button><span></span><button data-drive="left" aria-label="Putar kiri">←</button><button data-drive="back" aria-label="Mundur">↓</button><button data-drive="right" aria-label="Putar kanan">→</button></div><p class="muted">Mode Manual: tahan tombol untuk bergerak; kendali diambil otomatis. Lepas tombol untuk berhenti.</p><button id="stop" class="stop">STOP SEMUA</button></section>
<section class="card"><h2>Tangan & laser</h2><label for="armLeft">Tangan kiri <output id="armLeftValue">90°</output></label><input id="armLeft" type="range" min="0" max="180" value="90"><label for="armRight">Tangan kanan <output id="armRightValue">90°</output></label><input id="armRight" type="range" min="0" max="180" value="90"><label class="row"><input id="laser" type="checkbox"> Laser aktif</label><p class="muted">Mode Manual: slider langsung aktif. Sudut tangan kiri dibalik agar searah tangan kanan. Servo menahan sudut setelah stop.</p><h2>Status perangkat</h2><p class="muted warning">Angka berikut adalah output perintah, bukan posisi terukur.</p><pre id="status">Belum terhubung.</pre></section>
<section class="card wide"><h2>Firmware & konfigurasi</h2><label for="firmware">Binary aplikasi (.bin)</label><input id="firmware" type="file" accept=".bin"><button id="upload" style="margin-top:12px">Upload OTA</button><p class="muted">Motor, laser, dan pulsa servo dinonaktifkan selama update. Nonaktifkan ArduinoOTA sebelum upload web.</p><label><input id="arduinoOta" type="checkbox"> Aktifkan ArduinoOTA</label><details><summary>Pengaturan Wi-Fi router</summary><label for="ssid">SSID</label><input id="ssid" value="HuaweiJIN" readonly maxlength="32" autocomplete="off"><label for="wifiPassword">Password Wi-Fi</label><input id="wifiPassword" type="password" maxlength="63" autocomplete="new-password"><button id="saveWifi" style="margin-top:12px">Simpan Wi-Fi</button></details></section></div></main>
<script>
'use strict';
const el=id=>document.getElementById(id);
class RobotDashboard {
 constructor(request,notify,onSession=()=>{}){this.request=request;this.notify=notify;this.onSession=onSession;this.session=0;this.sequence=0;this.generation=0;this.timer=null;this.pending=false;this.acquiring=false;this.desired={left:0,right:0,arm_left:90,arm_right:90,laser:false};}
 async acquire(){if(this.session||this.acquiring)return;this.acquiring=true;const gen=this.generation;try{const r=await this.request('/control/acquire',{owner:'manual'});if(gen!==this.generation){await this.request('/control/release',{session:r.session});return;}this.session=r.session;this.sequence=0;this.onSession(true);this.notify('Manual aktif');await this.send();if(this.session)this.timer=setInterval(()=>this.send(),100);}catch(e){await this.stop();this.notify(e.message);}finally{this.acquiring=false;}}
 async send(){if(!this.session||this.pending)return;this.pending=true;const gen=this.generation;try{await this.request('/command',{session:this.session,sequence:++this.sequence,...this.desired});}catch(e){if(gen===this.generation){await this.stop();this.notify(e.message);}}finally{this.pending=false;}}
 async stop(){const session=this.session;++this.generation;clearInterval(this.timer);this.timer=null;this.session=0;this.desired.left=this.desired.right=0;this.desired.laser=false;this.onSession(false);try{if(session)await this.request('/control/release',{session});}catch(e){if(e.message!=='session_rejected')this.notify('Stop tidak terkirim; timeout perangkat akan menghentikan output.');}}
}
let connected=false,mode='manual',refreshing=false,switchingMode=false,uploading=false;
async function request(path,body){const abort=new AbortController();const timeout=setTimeout(()=>abort.abort(),1500);try{const response=await fetch('/api/v1'+path,{method:body===undefined?'GET':'POST',cache:'no-store',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:abort.signal});const result=await response.json();if(!response.ok)throw Error(result.error||'Permintaan ditolak');return result;}finally{clearTimeout(timeout);}}
const notify=text=>el('message').textContent=text;
function updateControls(){const manual=connected&&mode==='manual'&&!uploading&&!switchingMode;for(const button of document.querySelectorAll('[data-drive]'))button.disabled=!manual;for(const id of ['armLeft','armRight','laser'])el(id).disabled=!manual;el('acquire').disabled=!manual||!!controller.session;for(const selected of ['manual','auto']){const button=el(selected==='manual'?'modeManual':'modeAuto');button.disabled=!connected||uploading||switchingMode;button.classList.toggle('primary',mode===selected);button.setAttribute('aria-pressed',String(mode===selected));}el('laser').checked=!!controller.session&&controller.desired.laser;el('modeInfo').textContent=mode==='manual'?'Manual: tombol dan slider mengambil kendali otomatis.':'Auto: kendali melalui engine laptop/API. Tidak ada gerakan otomatis tanpa perintah engine.';}
const controller=new RobotDashboard(request,notify,()=>updateControls());
async function refresh(){if(refreshing||switchingMode||uploading||document.hidden)return;refreshing=true;const session=controller.session,gen=controller.generation;try{const s=await request('/status');if(switchingMode||uploading)return;const recovered=!connected;connected=true;mode=s.mode;el('version').textContent=s.firmware_version;el('connection').textContent='Terhubung · '+s.sta_ip;el('status').textContent=JSON.stringify(s,null,2);el('arduinoOta').checked=s.arduino_ota;const p=s.pwm;el('pwmInfo').textContent=p?'PWM roda: '+(p.ready&&p.write_ok?'siap':'gagal')+' · L '+Math.max(p.left1_duty,p.left2_duty)+'/1024 · R '+Math.max(p.right1_duty,p.right2_duty)+'/1024':'PWM roda: status tidak tersedia';if(session&&session===controller.session&&gen===controller.generation&&s.session!==session){await controller.stop();notify('Sesi berakhir: '+s.reason);}if(!controller.session&&!controller.acquiring){for(const [id,key] of [['armLeft','arm_left'],['armRight','arm_right']]){const value=s.commanded_output[key];el(id).value=value;el(id+'Value').value=value+'°';controller.desired[key]=value;}}updateControls();if(recovered)notify('Terhubung. Pilih Manual atau Auto.');}catch(e){connected=false;el('connection').textContent='Tidak terhubung · mencoba lagi';await controller.stop();updateControls();notify('Koneksi terputus: '+e.message);}finally{refreshing=false;}}
async function selectMode(next){if(switchingMode||uploading)return;switchingMode=true;updateControls();try{await controller.stop();await request('/control/mode',{mode:next});mode=next;notify(next==='manual'?'Mode Manual aktif.':'Mode Auto aktif; menunggu engine laptop.');}catch(e){notify(e.message);}finally{switchingMode=false;updateControls();await refresh();}}
el('modeManual').onclick=()=>selectMode('manual');el('modeAuto').onclick=()=>selectMode('auto');
el('connect').onclick=()=>refresh();el('acquire').onclick=()=>{if(connected&&mode==='manual')controller.acquire();};
el('stop').onclick=async()=>{await controller.stop();try{await request('/stop',{});notify('Output dihentikan.');await refresh();}catch(e){notify(e.message);}};
el('power').oninput=()=>{el('powerValue').value=el('power').value+'%';};
for(const id of ['armLeft','armRight'])el(id).oninput=async()=>{el(id+'Value').value=el(id).value+'°';if(!connected||mode!=='manual')return;controller.desired[id==='armLeft'?'arm_left':'arm_right']=Number(el(id).value);await controller.acquire();await controller.send();};
el('laser').onchange=async()=>{if(!connected||mode!=='manual'){el('laser').checked=false;return;}controller.desired.laser=el('laser').checked;await controller.acquire();await controller.send();};
for(const button of document.querySelectorAll('[data-drive]')){
 button.onpointerdown=async event=>{event.preventDefault();if(!connected||mode!=='manual')return;button.setPointerCapture(event.pointerId);const p=Number(el('power').value)/100;const dir=button.dataset.drive;controller.desired.left=dir==='back'||dir==='left'?-p:p;controller.desired.right=dir==='back'||dir==='right'?-p:p;await controller.acquire();await controller.send();};
 for(const type of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(type,()=>controller.stop());
}
window.addEventListener('blur',()=>controller.stop());document.addEventListener('visibilitychange',()=>{if(document.hidden)controller.stop();else refresh();});
window.addEventListener('pagehide',()=>{if(controller.session)fetch('/api/v1/control/release',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session:controller.session}),keepalive:true}).catch(()=>{});controller.stop();});
el('upload').onclick=async()=>{const file=el('firmware').files[0];if(!file){notify('Pilih binary aplikasi dahulu.');return;}await controller.stop();uploading=true;updateControls();const form=new FormData();form.append('firmware',file);const abort=new AbortController();const timeout=setTimeout(()=>abort.abort(),120000);try{notify('Upload berlangsung…');const r=await fetch('/api/v1/update',{method:'POST',body:form,signal:abort.signal});const data=await r.json();if(!r.ok)throw Error(data.error);connected=false;notify('Upload berhasil. Robot reboot dalam keadaan idle.');}catch(e){notify('Upload gagal: '+e.message);}finally{clearTimeout(timeout);uploading=false;updateControls();}};
el('arduinoOta').onchange=async()=>{try{await request('/settings',{arduino_ota:el('arduinoOta').checked});notify('Pengaturan ArduinoOTA disimpan untuk sesi boot ini.');}catch(e){notify(e.message);await refresh();}};
el('saveWifi').onclick=async()=>{await controller.stop();try{await request('/settings',{ssid:el('ssid').value,password:el('wifiPassword').value});el('wifiPassword').value='';notify('Profil HuaweiJIN diterapkan.');}catch(e){notify(e.message);}};
updateControls();refresh();setInterval(refresh,1000);window.RobotDashboard=RobotDashboard;
</script></body></html>)HTML";
